### ISSUE TITLE
VSCode Debug not working as expected

### ISSUE THREAD

**Issue by atul221282** [nestjs/typescript-starter#73] opened 2019-02-09 15:32 UTC
Created new project using nest cli and running **npm run start:debug** command but it is just sitting and doing nothing **npm run start:dev** works but then no debugging

with npm run start:debug the output is coming as below

![image](https://user-images.githubusercontent.com/4570393/52522610-873ca480-2cd7-11e9-9b88-b94d66f3921e.png)

This should be fix as per #37 but still not fixed and mentioned bug #37  should be reopen

**Comment by kamilmysliwiec** [comment] 2019-02-18 11:33
Duplicate of https://github.com/nestjs/nest/issues/1543

**Closed by kamilmysliwiec** 2019-02-18 11:33 UTC
